version: '3.8'
services:
  database:
    restart: always
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres:/var/lib/postgresql/data
  cache:
    image: redis
    restart: always
    ports:
      - '6379:6379'
    command: redis-server
    env_file:
      - .env
    volumes:
      - redis:/data
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/allygator-shuttle
    ports:
      - "3000:3000"
    depends_on:
      - database
      - cache
volumes:
  redis:
  postgres:
